### ISSUE TITLE
Error compatability

### ISSUE THREAD

**Issue by vampiregoat699** [spetzel2020/quick-encounters#126]
[quick-encounters] The module "quick-encounters" is using the old flat core compatibility fields which are deprecated in favor of the new "compatibility" object

**Comment by EarlOfEnums** [comment]
The compatibility fields are not the only compatibility issues with the module.json. There is an issue with the it using "name" instead of "id" and author instead of authors object array. I have fixed these issues here:
`{
  "id": "quick-encounters",
  "title": "Quick Encounters",
  "description": "<p>Keeps your Scene map clean and your encounters simple by saving tokens/Actors into Quick Encounter Journal Entries:</p><p><strong>NEW in v1.1:</strong>Supports Foundry 9 and 10</p><p>Default Journal Folder for new Quick Encounters; Add Actor RollTables from JEs; Bug fixes</p><br><ul><li>Design encounters by positioning and configuring Hostile tokens, then save the tokens into a Quick Encounter Journal Entry, marked with a single Map Note on the Scene which only you the DM see</li><li>Click the Run Quick Encounter button and all your saved tokens will be positioned back on the map and added to the Combat Tracker, ready to fight!</li><li>Run encounters from converted or packaged modules with embedded Actors</li><li>Easily scale-up encounters by changing 3 Zombies to 10 Zombies</li><li>Similar to the Encounter ability in Fantasy Grounds</li><li>For Roving Encounters move a single Map Note, not many tokens</li><li>Instant Encounters let you drag a Quick Encounter from Journals to the Scene and run it immediately</li><li>Flexible Settings control removing/leaving tokens, deleting all/defeated tokens after combat, and more!</li></ul>",
  "authors": [{ "name": "Spetzel" }],
  "version": "1.1.2",
  "compatibility": {
    "minimum": "9",
    "verified": "10"
  },
  "languages": [
    {
      "lang": "en",
      "name": "English",
      "path": "lang/en.json"
    },
    {
      "lang": "es",
      "name": "Español",
      "path": "lang/es.json"
    },
    {
      "lang": "ja",
      "name": "日本語",
      "path": "lang/ja.json"
    },
    {
      "lang": "de",
      "name": "Deutsch",
      "path": "lang/de.json"
    },
    {
      "lang": "it",
      "name": "Italian",
      "path": "lang/it.json"
    }
  ],
  "esmodules": [
    "modules/QuickEncounter.js",
    "modules/EncounterNote.js",
    "modules/QESheet.js"
  ],
  "styles": ["css/quick-encounters.css"],
  "readme": "https://github.com/spetzel2020/quick-encounters/blob/master/README.md",
  "allowBugReporter": true,
  "bugs": "https://github.com/spetzel2020/quick-encounters/issues",
  "changelog": "https://github.com/spetzel2020/quick-encounters/blob/master/CHANGELOG.md",
  "manifest": "https://github.com/spetzel2020/quick-encounters/releases/latest/download/module.json",
  "download": "https://github.com/spetzel2020/quick-encounters/releases/download/v1.1.2/quick-encounters.zip",
  "url": "https://github.com/spetzel2020/quick-encounters"
}
`

**Comment by spetzel2020** [comment]
Sorry, when you say "You've fixed them", do you mean in the comment? There's no PR for this I assume?

**Comment by EarlOfEnums** [comment]
Yes the comment is a replacement for your module.json. I'm not a member of your repo. I can't create a PR for it. Otherwise I would.

**Comment by spetzel2020** [comment]
Fixed in 1.1.3 (not yet released)
