### ISSUE TITLE
[Improvement suggestion] Default Journal using 10's new journal style (all Encounters added to it)

### ISSUE THREAD

**Issue by lucaspicerni** [spetzel2020/quick-encounters#128]
Hello! I love this module! It would be great if, to better integrate with the new journal design in V10, the module allowed you to create encounters notes as pages in a journal, rather than individual journals in a folder!

**Comment by spetzel2020** [comment]
I'm a little confused; you can already create Encounters on separate pages
of the V10 Journal and add notes/comments along with them. Is that what
you're talking about?

It is clunky to do so, because currently QE can't tell whether you want to
create a new Journal and corresponding Note, vs adding to an existing
Journal. So you have to manually create the page and drag Actors to the
page.
But let me know what you'd like and I'll see if there's a way to handle it.
There is an outstanding bug about this as well.

**Comment by lucaspicerni** [comment]
My suggestion is to implement precisely the possibility of skipping this manual task. For example, a configuration where it is possible to define a journal (just as it is already possible to define a folder) and create all encounters notes within this single journal.

**Comment by spetzel2020** [comment]
The next version of QE (v12) will be the last, and unfortunately I will not be fixing this enhancement.
