### ISSUE TITLE
Add Player Tokens option: Logged In doesn't work (adds all Tokens)

### ISSUE THREAD

**Issue by spetzel2020** [spetzel2020/quick-encounters#139]
Okay, took me a bit to find some time to test this, and my regular sessions didn't actually do any fighting where I used QE in the past week.

The "In Scene" settings works great, it adds all player tokens. However, the "Logged In" setting doesn't; it instead just also adds all player tokens.

I do get an error in the debug console. No idea if that's related, because it also appears with the "In Scene" settings.

```
Uncaught (in promise) TypeError: this.previous is undefined
[Detected 1 package: quick-encounters]
    _manageTurnEvents foundry.js:21481
    _onCreate foundry.js:21319
    callback foundry.js:13525
    documents foundry.js:13498
    #handleCreateDocuments foundry.js:13498
    _createDocuments foundry.js:13359
    create commons.js:8594
    createDocuments commons.js:7923
    create commons.js:8046
    toggleCombat foundry.js:42508
    toggleCombat foundry.js:55640
    createCombat QuickEncounter.js:1628
    run QuickEncounter.js:1225
    setTimeout handler*run QuickEncounter.js:1224
    activateListeners QESheet.js:126
    jQuery 9
    activateListeners QESheet.js:124
    _render foundry.js:5766
    _render foundry.js:6456
    _render QESheet.js:91
    render foundry.js:5693
    displayQEDialog QuickEncounter.js:1935
    onRenderJournalPageSheet QuickEncounter.js:1885
    #call foundry.js:730
    callAll foundry.js:687
    _renderPageViews foundry.js:74702
    _render foundry.js:74665
    render foundry.js:5693
    render foundry.js:7035
    _onClickLeft2 foundry.js:52453
    callback foundry.js:31655
    #handleClickLeft2 foundry.js:31860
    #handleMouseDown foundry.js:31827
    notifyListeners earcut.js:128
    notifyTarget earcut.js:128
    propagate earcut.js:128
    dispatchEvent earcut.js:128
    mapPointerDown earcut.js:128
    mapEvent earcut.js:128
    onPointerDown earcut.js:128
foundry.js:21481:19
```

_Originally posted by @DrMcCoy in https://github.com/spetzel2020/quick-encounters/issues/123#issuecomment-1703857205_

**Comment by spetzel2020** [comment]
Environment referenced: https://github.com/spetzel2020/quick-encounters/issues/123#issuecomment-1703857959

**Comment by spetzel2020** [comment]
This is occurring because right now "Logged In" looks at the ownership level of all tokens, and if an active player is marked as an Owner (or higher) then the token is added.

Can you let me know if this is the case for you? You would need to look at the access permissions for all PC tokens:

1. Find the PC Actor under Actors
2. Right-click and select `Configure Ownership`
3. Tell me what it says under `All Players` and also whether anybody except one player has `Owner` selected

**Comment by DrMcCoy** [comment]
It also happened with no player at all logged in, setting set to "Logged In", that still all player tokens get added.

The actors each have:
1. "Owner" for the actual player
2. "Observer" for All Player

Example:

![Screenshot 2023-09-17 at 11-36-32 Foundry Virtual Tabletop](https://github.com/spetzel2020/quick-encounters/assets/156130/d54b3f6c-b551-4287-8acd-6caa6c96dd55)

Oh, and they're all "Trusted Players" in the user config, in case that's important. I'm the sole user with Gamemaster levels.

Instead of looking at the ownership of the tokens, you might want to look at the "character" property of the user, from the game.users collection, instead. This tracks the assigned character in the user config, when right-clicking on a user in the "Players" box in the lower right (and IIRC, a selection pops up when a player with no character assigned logs in for the first time?). That's a direct 1:1 relationship that might more directly match what I'd expect from this setting, I think.

I recently did something similar for a custom macro for a "coin" I give out for good roleplay and the like, a "fate/bennie/luck" point that lets players re-roll a failed roll. I wanted the coin to post "[Player] added/spent a coin" on quantity change, and since I consider these coins a *player* resource and not an in-game *character* resource, I wanted it to write the user name and not the actor name.

The function I wrote for that is basically this:
```
function findOwnerName(actor) {
	const users = game.users.filter(u => u.role <= CONST.USER_ROLES.TRUSTED);
	
	const controllers = users.filter(u => u.character == actor);
	if (controllers)
		return controllers[0].name;

	return "";
}
```

Maybe you can adapt that for your use-case. Though you'd also probably want to filter on u.active == true as well, to filter out users that are not logged-in.

**Comment by spetzel2020** [comment]
Ah yes, I was wondering whether the assigned character might be a better
approach, and I agree is more what a user would expect.

Thanks for the thorough explanation and code!

**Comment by spetzel2020** [comment]
Fixed (not yet released) in 1.2.1c

**Comment by spetzel2020** [comment]
Released in 1.2.1 (but not yet made "latest"): 
Install https://github.com/spetzel2020/quick-encounters/releases/download/v1.2.1/module.json

**Comment by spetzel2020** [comment]
Updated to be Latest release

**Comment by DrMcCoy** [comment]
Okay, I was able to test it yesterday, and yes, it works now! Thanks! :D

**Comment by spetzel2020** [comment]
Wonderful - sorry it's taken so long.
