### ISSUE TITLE
Bug: Quick encounters stopping autofill of Map Pin Journal and Page fields

### ISSUE THREAD

**Issue by StevenEvans1966** [spetzel2020/quick-encounters#141]
**Core Foundry**
![image](https://github.com/spetzel2020/quick-encounters/assets/81326195/d52546d9-2e84-41f1-b092-d4b76afa26a2)
**QE**
![image](https://github.com/spetzel2020/quick-encounters/assets/81326195/6a196d49-1272-4795-8990-29178f66fa4c)

**Comment by spetzel2020** [comment]
To check:

- Is the problem that QE Map Notes do not have these auto-filled
- OR that with QE enabled, ALL Map Notes no longer have autofills?

**Comment by StevenEvans1966** [comment]
It effects none QE pins

**Comment by spetzel2020** [comment]
I can't reproduce this problem when I tried creating the QE through two methods:
1. Select hostile tokens and then press the QE button (crossed swords); you don't see the QE Note during creation but when I check it afterwards it has a Journal but no Page (because no Page exists yet)
2. Drag a JE with an Encounter to the Scene; you get a dialog whether to run an Instant Encounter or create a QE Note. When I create QE Note it is correctly populated

It sounds like perhaps you are creating QE Notes a different way; can you provide me steps to reproduce in this Issue?

**Comment by spetzel2020** [comment]
Unable to reproduce; please feel free to reply with the steps and I will reopen

**Comment by spetzel2020** [comment]
Unable to reproduce; please feel free to reply with the steps and I will reopen
