### ISSUE TITLE
[BUG?] What am I doing wrong?

### ISSUE THREAD

**Issue by mjeffw** [spetzel2020/quick-encounters#38]
I'm trying to use this cool module, but weird stuff happens on my scenes that I cannot get rid of.

I'm not sure exactly what sequence of events I've done but here's what I was attempting to do:

I've create a scene and put 8 giant centipedes in it. I've create a journal and selected the centipedes and then clicked the Quick Encounter button. So far so good. 

I had to recreate my journal entry at some point, so deleted the actors out of it and recreated it using the steps above.

Now I have several icons on the scene which I don't know what they are. See the attached image.
![image](https://user-images.githubusercontent.com/7349413/109401057-71c86080-791a-11eb-80d5-b79503d62647.png)

I know one of these is my journal entry. What's the big red thing? Why can't I remove any of the three icons?

**Comment by mjeffw** [comment]
Also: I don't understand what the checkmarks are for in this dialog:

![image](https://user-images.githubusercontent.com/7349413/109401154-0206a580-791b-11eb-929a-48c832509aad.png)

**Comment by mjeffw** [comment]
Another question: sometimes the saved token positions is off. How do I prevent this from happening, and is there a way to reset the positions of the tokens?

**Comment by spetzel2020** [comment]
Hello, and sorry for the delay in responding.

Answering your questions in order:
1. The sword-and-shield icon (Map Note) is the one automatically created by QE when you create a new Quick Encounter; it's placed where the first token and you can double-click it to open the Quick Encounter. I'm not sure why you have three icons because I don't know your sequence of actions. 
2. To DELETE it, you have to switch to the Journal Notes controls (the bottom one in the Basic Controls vertical ribbon on the left). Then select it and press Delete.
3. The checkboxes represent the fact that there are saved Tokens; you can have generated Tokens also, which are placed randomly around the Map Note on the Scene. Try this by changing the number of actors from 8 to a greater number.
4. the [Save] button saves changes to the number of Actors; some dialogs in Foundry (this is one of them) don't Save and Close; you have to Close/Cancel the dialog separately.
5. I'm not sure what you mean by "saved token positions is off"; do you mean when you run the Encounter, or something else?

Feel free to ping me on Discord and we can walk through this together. I'm on U.S. Pacific Time.
