### ISSUE TITLE
Unwanted dialog box

### ISSUE THREAD

**Issue by pixel7777** [spetzel2020/quick-encounters#4]
Every time I close any journal entry, regardless of how or when it was created, I get a prompt:
"I didn't find a corresponding note for this quick encounter.  Do you want to create a default Note in the center of your view?"
I have no idea why it's asking this for EVERY journal entry.  
It also adds a quick encounter header to every entry in which I have actors.  Can there be a way to indicate if a journal entry is a quick encounter entry or not, because this is very intrusive?

**Comment by opus1217** [comment]
Thanks for the feedback!
Quick Encounters assumes any Journal Entry with embedded Actors is a possible Quick Encounter, so asks the question about the Map Note and adds the extra button. But I recognize that can be intrusive and annoying, so:
- Re the "Do you want to create a Default Note...", is that happening for Journal Entries with Actors, or for every Journal Entry including those **without** Actors? It's meant to happen only for those with Actors

The solution I had been planning was to have some options in Configure Settings:
[ ] Add Quick Encounter section (with button) to Quick Encounter Journal Entries
[ ] Ask the question about placing a Map Note
**What do you think?** The other option is that you have to specifically designate a Journal Entry as a Quick Encounter Journal Entry (if you use Method 2 with just embedded Actors). I have to think about what the UI would be for that - I welcome suggestions,

**Comment by pixel7777** [comment]
The pop up is happening only with journal entries with embedded actors, so it's functioning as you intended, but I have LOTS of actors embedded in entries that I don't want to be a quick encounter.  And the pop up happens even if I just opened the entry and then closed it again.  At a minimum, I would provide the open to remove the question altogether in configuration, as you suggested or only do the pop up for an entry that has been edited (not just opened and read).  
Honestly, I think you could do more with this application if a quick encounter entry was a specialized type of entry, in the same way that a loot actor is a specialized type of actor and an Easy Table is a specific kind of table.  These both use a different button to create them and pop up a unique UI that is suited to their specialization.  Another good model to follow is Better Roll Tables, which adds a drop down to the normal table creation screen that lets you specify if it's a specific type of Better Table, or just a regular roll table.  Then, for example, you could have a specific section for which actors are part of the encounter (other links in the same entry might just be there for reference).  Or an option to specify a deployment pattern (randomly near the pin, in a line west of the pin, etc).  Maybe even an option to do a text search of the entry and auto-link matching actors and place them as candidates in an encounter section (would be great for converting text from published adventures into playable encounter entries.
Right now the constant pop ups are bugging me too much to leave the module on, but I would particularly like this for deploying a party to a scene (I am running Tomb of Annihilation, and a "party" might be a 25 member expedition) and for roving patrols.  I love the concept and am excited to see what you do with it next!

**Comment by opus1217** [comment]
Love the suggestions and the interest. Specific answers:

1.  _Right now the constant pop ups are bugging me too much to leave the module on,_ Completely makes sense, and I will prioritize an option to turn off the "Do you want to place a map Note?" or make it a self-dismissing dialog. I can even move that question to when you actually try to run the Quick Encounter because that's when you need to have the anchor
2.  _I think you could do more with this application if a quick encounter entry was a specialized type of entry_ Very true. I was trying to avoid a completely separate setup process because of trying to handle the use-case like yours, of having MANY entries with Actors, and just wanting to use them. But I could definitely attach a specialized pop-up to Journal Entries you designate in this way, with the sort of options for the deployment pattern etc. That would also solve a UI problem, because I want to add a separate dialog showing which Actors have already been positioned (akin to Fantasy Grounds Encounter feature)
3. _option to do a text search of the entry and auto-link matching actors_Yes, definitely! This was on my planned features list!

I appreciate the detailed feedback and will let you know when I have something that you might be interested in looking at again.

**Comment by opus1217** [comment]
Will split specific ideas into separate Issues.

**Comment by spetzel2020** [comment]
Closing this issue because it has been  fixed or incorporated into other open ones
