### ISSUE TITLE
[Suggestion/Request] Work with roll tables

### ISSUE THREAD

**Issue by winterwulf** [spetzel2020/quick-encounters#40]
If possible trigger roll tables linked to the journal entry and insert the tokens from the tables result

**Comment by JaySK015** [comment]
This would be a great feature if it doesn't already exist.  Thank you for your great work on Quick Encounters!

**Comment by spetzel2020** [comment]
Musing: A possible way to do this would be to add all the Actors (and optionally their Tokens) to the QE, and then have the Rolltable choose which one of the Actors actually shows up.

Another alternative would be to have a Rolltable as the option for one or more of the Actors, with the Rolltable generating how **many** Actors show up (including possibly zero)

**Comment by spetzel2020** [comment]
Looking at this as part of 1.1; seems like the right way to do this is to link a Rolltable in the same way you can add Tokens or Tiles.

**Comment by spetzel2020** [comment]
Possible implementation:
1. Create a RollTable with a list of actors of equivalent CR
2. Create a vanilla Journal Entry (or at least one without an existing Quick Encounter)
3. Drag the Rolltable into the Journal Entry. Prepend a number of die roll to indicate how many of the creatures from the roll (note that all will have the same number appearing because there's no way of embedding different numbers in the Rolltable)
4. Now change QE so it recognizes a RollTable just like it does an Actor or Tile. 
5. When you click Run Quick Encounter, have to insert an intermediate step of generating the actor from the RollTable.

**Comment by spetzel2020** [comment]
Basic working in 1.1.1f (not yet released). 
Need to add:
- Make the number field editable like Actors (including die rolls)
- Save to the QuickEncounter (may already be happening)
- Remove - isn't showing on the icon (may need to be semi-transparent - check style)

**Comment by spetzel2020** [comment]
Above changes included in 1.1.1g

**Comment by spetzel2020** [comment]
Released in 1.1.1
